sudo: false
language: python

#cache:
#  directories:
#  - "$HOME/google-cloud-sdk/"

env:
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1 HTTP_HOST=localhost APPENGINE_LIB=${HOME}/google-cloud-sdk/platform/google_appengine

before_install:
#  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
#      curl https://sdk.cloud.google.com | bash;
#      gcloud components install app-engine-python;
#    fi
  - curl https://sdk.cloud.google.com | bash;
  - gcloud components install app-engine-python;

install:
  - cd ${TRAVIS_BUILD_DIR}/python; ./build.sh deps

script:
  - cd ${TRAVIS_BUILD_DIR}/python; ./build.sh test
